name: HeliEnchanting
version: '1.1.0'
main: ru.helicraft.helienchanting.HeliEnchanting
bootstrapper: ru.helicraft.helienchanting.bootstrap.HeliEnchantingBootstrap
api-version: '1.21.11'
authors: [ ms0ur, Ktilis ]
description: ''
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
